# Generated by Django 3.2 on 2021-05-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroicaTour_DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
