# Generated by Django 3.2 on 2021-05-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroicaTour_DB', '0002_alter_hotel_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitioturistico',
            name='Categoria',
            field=models.CharField(choices=[('Centros Comerciales', 'Centros Comerciales'), ('Playas', 'Playas'), ('Turistico', 'Turistico'), ('Centro Historico', 'Centro Historico')], default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='Rol',
            field=models.CharField(choices=[('Guia', 'Guia'), ('Soporte', 'Soporte'), ('Admin', 'Admin')], default=None, max_length=25),
        ),
    ]
