# Generated by Django 3.2 on 2021-05-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroicaTour_DB', '0003_auto_20210505_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxi',
            name='Barrio_currency',
        ),
        migrations.AlterField(
            model_name='taxi',
            name='Barrio',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
