# Generated by Django 3.2 on 2021-05-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroicaTour_DB', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
